import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";
import { QueryProvider } from "@/components/QueryProvider/QueryProvider";
import { GlobalContextProvider } from "@/components/GlobalContextProvider";
import { ClerkProvider } from '@clerk/nextjs'
import { SideBarWrapper } from "@/components/SideBar/SideBarWrapper"
import { Toaster } from "@/components/ui/toaster"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "World Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
          <QueryProvider>
            <GlobalContextProvider>
              <SideBarWrapper>
                {children}
              </SideBarWrapper>
              <Toaster />
            </GlobalContextProvider>
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
