import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Styles from './styles.module.css'
import PersistentDrawerLeft from "./test/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "World Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={Styles.columns}>
          <PersistentDrawerLeft>
            {children}
          </PersistentDrawerLeft>
        </div>
      </body>
    </html>
  );
}
